### ISSUE TITLE
Error: Can't resolve 'net' in ...

### ISSUE THREAD

**Issue by wiiiimm** [tgorka/node-window-polyfill#3]
`import "node-window-polyfill/register";` was inserted into the code and I get a `Can't resolve 'net'`

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'net' in '/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/ws/lib'
    at factoryCallback (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/async/dist/async.js:3888:9
    at /Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/async/dist/async.js:1062:13)
    at /Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/async/dist/async.js:969:16
    at /Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/williamli/projects/bbiHQ/exchangeunion-frontend/node_modules/tapable/lib/Tapable.js:252:11)
```

**Comment by tgorka** [comment]
@williamli Is it all stack trace? Do you have a gist with the code to identify the problem? It's hard to see the problem with this setup for me right now.
Btw. are you using it in the frontend?

**Comment by logandeancall** [comment]
I'm also getting this error. Looks like an issue with the `ws` dependency?

```
ERROR in ./node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'net' in '/home/user/universal/node_modules/ws/lib'
 @ ./node_modules/ws/lib/websocket.js 7:12-26
 @ ./node_modules/ws/index.js
 @ ./node_modules/node-window-polyfill/index.js
 @ ./node_modules/node-window-polyfill/register.js
 @ ./src/index.tsx

ERROR in ./node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'tls' in '/home/user/universal/node_modules/ws/lib'
 @ ./node_modules/ws/lib/websocket.js 8:12-26
 @ ./node_modules/ws/index.js
 @ ./node_modules/node-window-polyfill/index.js
 @ ./node_modules/node-window-polyfill/register.js
 @ ./src/index.tsx
```

**Comment by NHuebner1983** [comment]
Hi!  I was hoping this would have something figured out. Anyone know how to fix this? using register(false) and register(true) have the same error.

I am going to look into figuring it out because I'm running out of options, and this was my last hope - needing it for a nativescript-vue app that has dependencies trying to use the window object (third party vendors).   

I will post my updates soon if it helps anyone.

**Comment by tgorka** [comment]
I updated the libraries. That might help. If anyone will have this issue please get reach me out (page in my profile) for a fast solving issue.
